"""add ip rate limiting table

Revision ID: b8f7c96e088c
Revises: ef935f3f961b
Create Date: 2026-01-17 08:46:10.780416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f7c96e088c'
down_revision = 'ef935f3f961b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_rate_limits_ip'), ['ip'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_rate_limits_ip'))

    op.drop_table('ip_rate_limits')
    # ### end Alembic commands ###
