"""add last_seen_at to sessions

Revision ID: db47a9bd2241
Revises: 79ff159e2809
Create Date: 2026-01-15 14:35:13.369293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db47a9bd2241'
down_revision = '79ff159e2809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')

    # ### end Alembic commands ###
